### ISSUE TITLE
Telegram chatId ignored

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [St0Ma/ioBroker-MessageHandler#1]
In massagehandler.js line 1314 **{ChatId:** needs to be replaced with **{chatId:**  (lowercase c)
Currently it is ignored by the Telegram adapter
[Direct Link](https://github.com/St0Ma/ioBroker-MessageHandler/blob/a1c68261c2fa7e9f89874f61bc7f955e32362f37/MessageHandler.js#L1314)

                 
```
 if (telegramChatId.length > 0) {
                        sendTo(telegramInstance, {ChatId: telegramChatId, text: telegramMsg, parse_mode: 'Markdown'}   );
                    }
```

**Comment by St0Ma** [comment]
Thx for reporting. Fixed in the next Version ;)
