### ISSUE TITLE
Statt View-Wechsel ein Dialog-View

### ISSUE THREAD

**Issue by Starcon79** [St0Ma/ioBroker-MessageHandler#2]
Hallo,
wäre es möglich statt dem View-Wechsel ein Dialog-View zu integrieren? 
Ich benutze nicht die Topappbar von Uhula sondern die von den Material-Design-Widgets von Scrounger dadurch ist es mir nicht möglich den View-Wechsel zu nutzen.
Wäre toll wenn du das noch einbauen könntest.
Sollten noch fragen sein einfach melden.

**Comment by St0Ma** [comment]
Verwende die Scrounger-Komponenten leider nicht und kann daher keine Lösung beitragen.
